version = "Two"
use_field_init_shorthand = true
imports_granularity="Crate"
wrap_comments = true
use_try_shorthand = true
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
