accepted = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Zlib",
    "0BSD",
]
workarounds = ["ring", "rustls"]

ignore-build-dependencies = true
ignore-dev-dependencies = true

[option-ext]
accepted = ["MPL-2.0"]

[ring]
accepted = ["ISC", "OpenSSL"]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]

[webpki]
accepted = ["ISC", "BSD-3-Clause"]

[webpki.clarify]
license = "ISC AND BSD-3-Clause"

[[webpki.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "5B698CA13897BE3AFDB7174256FA1574F8C6892B8BEA1A66DD6469D3FE27885A"

[[webpki.clarify.files]]
path = "third-party/chromium/LICENSE"
license = "BSD-3-Clause"
checksum = "845022E0C1DB1ABB41A6BA4CD3C4B674EC290F3359D9D3C78AE558D4C0ED9308"

[webpki-roots]
accepted = ["MPL-2.0"]
