status = [
    "fmt",
    "licenses_and_advisories (advisories)",
    "licenses_and_advisories (bans licenses sources)",
    "linter",
    "msrv",
    "test (ubuntu-stable)",
    "test (macos-stable)",
    "test (win-gnu-stable)",
    "test (win-msvc-stable)",
    "test (ubuntu-beta)",
    "test (ubuntu-nightly)",
]
