status = [
    "test (msrv)",
    "test (stable)",
    "test (beta)",
    "test (nightly)",
    "test (macos)",
    "test (win-gnu)",
    "test (win-msvc)",
    "rustfmt",
    "clippy",
    "cargo_deny (advisories)",
    "cargo_deny (bans licenses sources)",
    "msrv"
]

[committer]
name = "Martijn"
email = "garm@ilumeo.com"