name: "ci-coverage"
on:
  pull_request:
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4

      - name: install_rust_nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-01 # pinned because of https://github.com/tkaitchuck/aHash/issues/200#issuecomment-1936283358

      - name: install_code_coverage_tool
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: generate_code_coverage
        # `--lib` ensures we only run unit tests, no integration tests.
        # Integration tests are disabled, because they rely on Rust toolchains which do not support the rustc option
        # `-C instrument-coverage`, needed by llvm-cov.
        run: cargo llvm-cov --all-features --locked --lcov --output-path lcov.info --lib

      - name: upload_code_coverage
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
